name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Frontend - Prettier Check
        run: npm run prettier:check --workspace=apps/frontend

      - name: Frontend - ESLint
        run: npm run lint --workspace=apps/frontend

      - name: Backend - Prettier Check
        run: npm run prettier:check --workspace=apps/backend

      - name: Backend - ESLint
        run: npm run lint --workspace=apps/backend
